

-- 관리자 화면의 심사관리 / 심사대기 상태의 리스트 조회 쿼리
SELECT 
	LOAN.LOAN_CODE LOANCODE,JUDGE.JUDGE_SEQ JUDGESEQ,LOAN.EMAIL,MEMBER.NAME,MEMBER.BIRTH,MEMBER.GENDER,
	LOAN.PROGRESS,LOAN.EMPLOY_TYPE EMPLOYTYPE,LOAN.SCALE,LOAN.SERVE,LOAN.SALARY,LOAN.LOAN_TYPE LOANTYPE,
	LOAN.REPAY_TYPE REPAYTYPE,LOAN.INTEREST_RATE INTERESTRATE,LOAN.LOAN_MONEY LOANMONEY,LOAN.LOAN_DATE LOANDATE,LOAN.REPAY,
	LOAN.TITLE,LOAN.FNAME,LOAN.INTRO,	LOAN.EXPIRY_DATE EXPIRTYDATE,MEMBER.CREDIT_RATING CREDITRATING
FROM
	ABC_LOAN LOAN, ABC_JUDGE JUDGE, ABC_MEMBER MEMBER
WHERE
	JUDGE.LOAN_CODE = LOAN.LOAN_CODE
	AND JUDGE.RESULT=0
	AND MEMBER.EMAIL = LOAN.EMAIL;
	
-- 관리자 화면의 심사관리 / 심사대기 상태의 개별심사건 상세 내용 조회 쿼리
SELECT
	JUDGEDETAIL.LOANCODE,JUDGEDETAIL.JUDGESEQ,JUDGEDETAIL.EMAIL,JUDGEDETAIL.NAME,JUDGEDETAIL.BIRTH,JUDGEDETAIL.GENDER,
	JUDGEDETAIL.PROGRESS,JUDGEDETAIL.EMPLOYTYPE,JUDGEDETAIL.SCALE,JUDGEDETAIL.SERVE,JUDGEDETAIL.SALARY,JUDGEDETAIL.LOANTYPE,
	JUDGEDETAIL.REPAYTYPE,JUDGEDETAIL.INTERESTRATE,JUDGEDETAIL.LOANMONEY,JUDGEDETAIL.LOANDATE,JUDGEDETAIL.REPAY,
	JUDGEDETAIL.TITLE,JUDGEDETAIL.FNAME,JUDGEDETAIL.INTRO,JUDGEDETAIL.EXPIRTYDATE,JUDGEDETAIL.CREDITRATING 
FROM
	(SELECT 
		LOAN.LOAN_CODE LOANCODE,JUDGE.JUDGE_SEQ JUDGESEQ,LOAN.EMAIL,MEMBER.NAME,MEMBER.BIRTH,MEMBER.GENDER,
		LOAN.PROGRESS,LOAN.EMPLOY_TYPE EMPLOYTYPE,LOAN.SCALE,LOAN.SERVE,LOAN.SALARY,LOAN.LOAN_TYPE LOANTYPE,
		LOAN.REPAY_TYPE REPAYTYPE,LOAN.INTEREST_RATE INTERESTRATE,LOAN.LOAN_MONEY LOANMONEY,LOAN.LOAN_DATE LOANDATE,LOAN.REPAY,
		LOAN.TITLE,LOAN.FNAME,LOAN.INTRO,	LOAN.EXPIRY_DATE EXPIRTYDATE,MEMBER.CREDIT_RATING CREDITRATING
	FROM
		ABC_LOAN LOAN, ABC_JUDGE JUDGE, ABC_MEMBER MEMBER
	WHERE
		JUDGE.LOAN_CODE = LOAN.LOAN_CODE
		AND JUDGE.RESULT=0
		AND MEMBER.EMAIL = LOAN.EMAIL) JUDGEDETAIL
WHERE LOANCODE = 16;